audit_header: false
title: Sandy and Company Real Estate Video Blog
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Sandy and Company - your professional Marysville Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: "Sandy's Toolshed"
    url: /toolshed
  - title: "Testimonials"
    url: /client-testimonials
client:
  name: Sandy Eagon
  license_number:
  about_markdown:
  market:
  brand: 'Sandy &amp; Company'
  brokerage: KW Northwest
  brokerage_image: /img/KW_Northwest_Logo.png
  address: '1027 State Avenue Unit 102<Br>Marysville, WA 98270'
  phone: 425-422-7372
  email: Sandy@SandyAndCompany.com
  url:
  first_CTA_text: Home Evaluation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

# emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808112';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/SandyandCompany'
  linkedin_url: 'https://www.linkedin.com/pub/sandy-and-company/8/113/511'
  gplus_url: 'https://plus.google.com/114330374352693742825'
  youtube_url: 'https://www.youtube.com/channel/UCvVvyzOKkp4tKjzp4SpOmiQ'
  twitter_url: 'https://twitter.com/SandyEagon3'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/SandyandCompany/Reviews/'
  trulia_url: 'http://www.trulia.com/profile/sandy-eagon-agent-marysville-wa-zgm3z2wc/overview'
  yelp_url:
  podcast_url: 'https://itunes.apple.com/us/podcast/marysville-real-estate-podcast-sandy-eagon/id1203343775?mt=2'
podcast:
  title: Marysville Real Estate Podcast Sandy Eagon
  categories: Education
  image: /img/Eagon_Podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Marysville Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Sandy &amp; Company Real Estate - your professional Marysville Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Sandy Eagon
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text: Real Estate Video Blog
  hero_background_hex: '#b40101'
  hero_image_path: /img/banner.png
brand_color: '#b40101'
theme_color: '#ffffff'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
